filter:
    paths: [src/*]
    excluded_paths: [app/cache/*, vendor/*, vagrant-ansible/*]
before_commands:
    - 'composer install --prefer-source --no-interaction'
checks:
    php:
        code_rating: true
        duplication: true
tools:
    external_code_coverage: true